global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # AlertManager service will be added in future phases

rule_files:
  # Will be added in future phases

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tariffs-data-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['data-service:9090']
    scrape_interval: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']